LuanVan/Areas/AdminManage/Pages/User/AddRole.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LuanVan.Data;
using LuanVan.Models;
using LuanVan.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace LuanVan.Areas.AdminManage.Pages.User
{
    [Authorize(Roles = "Admin")]


    public class AddRoleModel : PageModel
    {
        private readonly UserManager<KhachHang> _userManager;
        private readonly SignInManager<KhachHang> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyf;
        private readonly LanguageService _localization;
        public AddRoleModel(
            UserManager<KhachHang> userManager,
            SignInManager<KhachHang> signInManager,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context,
            INotyfService notyf,
            LanguageService localization)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
            _notyf=notyf;
            _localization= localization;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>


        public KhachHang user { get; set; }

        [BindProperty]
        public string[] RoleNames { get; set; }

        public List<string> allRoles { get; set; }

        public List<IdentityRoleClaim<string>> claimsInRole { get; set; }

        public List<IdentityUserClaim<string>> claimsInUserClaim { get; set; }


        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }


            RoleNames = (await _userManager.GetRolesAsync(user)).ToArray<string>();

            List<string> roleName = await _roleManager.Roles.Select(x => x.Name).ToListAsync();

            allRoles= roleName.ToList();

            await GetClaims(id);


            return Page();
        }


        async Task GetClaims(string id)
        {
            var listRole = from r in _context.Roles
                           join ur in _context.UserRoles on r.Id equals ur.RoleId
                           where ur.UserId == id
                           select r;


            var _claimsInRole = from c in _context.RoleClaims
                                join r in listRole on c.RoleId equals r.Id
                                select c;

            claimsInRole = await _claimsInRole.ToListAsync();

            claimsInUserClaim = await (from c in _context.UserClaims
                                       where c.UserId == id
                                       select c).ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {

            if (string.IsNullOrEmpty(id))
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            await GetClaims(id);

            var OldRoleNames = (await _userManager.GetRolesAsync(user)).ToArray();

            var deleteRoles = OldRoleNames.Where(r => !RoleNames.Contains(r));

            var addRoles = RoleNames.Where(r => !OldRoleNames.Contains(r));

            List<string> roleName = await _roleManager.Roles.Select(x => x.Name).ToListAsync();

            allRoles = roleName.ToList();

            var resultDelete = await _userManager.RemoveFromRolesAsync(user, deleteRoles);
            if (!resultDelete.Succeeded)
            {
                resultDelete.Errors.ToList().ForEach(error =>
                {
                    ModelState.AddModelError(string.Empty, error.Description);

                });
                return Page();
            }


            var resultAdd = await _userManager.AddToRolesAsync(user, addRoles);
            if (!resultAdd.Succeeded)
            {
                resultAdd.Errors.ToList().ForEach(error =>
                {
                    ModelState.AddModelError(string.Empty, error.Description);

                });
                return Page();
            }

            //await _signInManager.RefreshSignInAsync(user);
            _notyf.Success(_localization.Getkey("UpdateRoleForUser")+ " " + user.UserName + " "+ _localization.Getkey("Thanhcong"));
            //StatusMessage = _localization.Getkey("UpdateRoleForUser") + " " + user.UserName+ " "+ _localization.Getkey("When") + " "+DateTimeVN();

            return RedirectToPage("./Index");
        }

        public DateTime DateTimeVN()
        {
            DateTime utcTime = DateTime.UtcNow; // Lấy thời gian hiện tại theo giờ UTC
            TimeZoneInfo vietnamZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time"); // Lấy thông tin về múi giờ của Việt Nam
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(utcTime, vietnamZone); // Chuyển đổi giá trị DateTime từ múi giờ UTC sang múi giờ của Việt Nam

            return vietnamTime;
        }
    }
}

LuanVan/Areas/AdminManage/Pages/User/ConfirmAccount.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using DocumentFormat.OpenXml.InkML;
using LuanVan.Data;
using LuanVan.Models;
using LuanVan.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Text.Encodings.Web;

namespace LuanVan.Areas.AdminManage.Pages.User
{
    [Authorize(Roles = "Admin")]
    public class ConfirmAccountModel : PageModel
    {
        private readonly UserManager<KhachHang> _userManager;
        private readonly SignInManager<KhachHang> _signInManager;
        private readonly INotyfService _notyf;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly LanguageService _localization;


        public ConfirmAccountModel(
            UserManager<KhachHang> userManager,
            SignInManager<KhachHang> signInManager,
            INotyfService notyf,
            ApplicationDbContext context,
            IEmailSender emailSender, LanguageService localization)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _notyf= notyf;
            _context = context;
            _emailSender= emailSender;
            _localization= localization;
        }

        [TempData]
        public string StatusMessage { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public string? KhachHangID { get; set; }
            public bool Confirm { get; set; }
        }

        public KhachHang user { get; set; }
        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }
            else
            {
                Input = new InputModel()
                {
                    KhachHangID= user.Id,
                    Confirm = user.EmailConfirmed
                };
                return Page();
            }
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {

            if (string.IsNullOrEmpty(id))
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                _notyf.Error(_localization.Getkey("KhongTimThay"), 3);
                return RedirectToPage("./Index");
            }

            var oldDisableAccount= user.EmailConfirmed;
            if(oldDisableAccount != Input.Confirm)
            {
                _context.Update(user);
                user.EmailConfirmed = Input.Confirm;
                await _context.SaveChangesAsync();

                //StatusMessage = _localization.Getkey("CapNhatXacThuc") +"" + DateTimeVN();
                _notyf.Success(_localization.Getkey("CapNhatXacThuc2") +"", 3);
            }
            else
            {
                //StatusMessage = _localization.Getkey("Sttnotchange");
                _notyf.Information(_localization.Getkey("Sttnotchange"), 3);
            }

            return RedirectToPage("./Index");
        }

        public DateTime DateTimeVN()
        {
            DateTime utcTime = DateTime.UtcNow; // Lấy thời gian hiện tại theo giờ UTC
            TimeZoneInfo vietnamZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time"); // Lấy thông tin về múi giờ của Việt Nam
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(utcTime, vietnamZone); // Chuyển đổi giá trị DateTime từ múi giờ UTC sang múi giờ của Việt Nam

            return vietnamTime;
        }

    }
}

LuanVan/Areas/AdminManage/Pages/User/EditUserRoleClaim.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LuanVan.Data;
using LuanVan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Security.Claims;

namespace LuanVan.Areas.AdminManage.Pages.User
{
    [Authorize(Roles = "Admin")]

    public class EditUserRoleClaimModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<KhachHang> _userManager;
        private readonly INotyfService _notyf;


        public EditUserRoleClaimModel(ApplicationDbContext context, UserManager<KhachHang> userManager, INotyfService notyf)
        {
            _context = context;
            _userManager = userManager;
            _notyf= notyf;
        }


        [TempData]
        public string StatusMessage { get; set; }

        public NotFoundObjectResult OnGet() => NotFound("Không được truy cập");

        public class InputModel
        {
            [Required(ErrorMessage = "Kiểu (tên) claim là bắc buộc")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "Tên (vai trò) role phải dài từ 3 đến 256 ký tự!")]
            public string ClaimType { get; set; }

            [Required(ErrorMessage = "Giá trị của claim là bắt buộc!")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "Tên (vai trò) role phải dài từ 3 đến 256 ký tự!")]
            public string ClaimValue { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public KhachHang user { get; set; }

        public async Task<IActionResult> OnGetAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);

            if (user == null)
                return NotFound("Không tìm thấy user");

            return Page();
        }

        public async Task<IActionResult> OnPostAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);

            if (user == null)
                return NotFound("Không tìm thấy user");

            if (!ModelState.IsValid)
                return Page();

            var claims = _context.UserClaims.Where(c => c.UserId == userid);

            if (claims.Any(c => c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue))
            {
                _notyf.Error("Claim " + Input.ClaimType + " :" + Input.ClaimValue + " đã tồn tại");
                ModelState.AddModelError(string.Empty, "Claim này đã tồn tại");
                return Page();
            }

            await _userManager.AddClaimAsync(user, new Claim(Input.ClaimType, Input.ClaimValue));
            StatusMessage = "Đã thêm claim " + Input.ClaimType + " :" + Input.ClaimValue + " thành công cho user "+ user.UserName;
            _notyf.Success("Đã thêm claim " + Input.ClaimType + " :" + Input.ClaimValue + " thành công cho user "+ user.UserName + " lúc "+ DateTimeVN());

            return RedirectToPage("./AddRole", new { Id = user.Id });

        }

        public IdentityUserClaim<string> userClaim { get; set; }

        public async Task<IActionResult> OnGetEditClaimAsync(int? claimid)
        {
            if (claimid == null)
                return NotFound("Không tìm thấy claim");

            userClaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            user = await _userManager.FindByIdAsync(userClaim.UserId);

            if (user == null)
                return NotFound("Không tìm thấy user");

            Input = new InputModel()
            {
                ClaimType = userClaim.ClaimType,
                ClaimValue = userClaim.ClaimValue,
            };
            return Page();
        }

        public async Task<IActionResult> OnPostEditClaimAsync(int? claimid)
        {
            if (claimid == null)
                return NotFound("Không tìm thấy claim");

            userClaim = await _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefaultAsync();

            user = await _userManager.FindByIdAsync(userClaim.UserId);

            if (user == null)
                return NotFound("Không tìm thấy user");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (_context.UserClaims.Any(c => c.UserId == user.Id && c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue && c.Id != userClaim.Id))
            {
                _notyf.Error("Claim " + Input.ClaimType + " :" + Input.ClaimValue + " đã tồn tại");
                ModelState.AddModelError(string.Empty, "Claim này đã tồn tại");
                return Page();
            }


            userClaim.ClaimType = Input.ClaimType;
            userClaim.ClaimValue = Input.ClaimValue;

            await _context.SaveChangesAsync();

            _notyf.Success("Cập nhật claim riêng cho user " + user.UserName + " thành công");
            StatusMessage = "Cập nhật claim riêng cho user " + user.UserName + " thành công lúc " + DateTimeVN() ;

            return RedirectToPage("./AddRole", new { Id = user.Id });

        }

        public async Task<IActionResult> OnPostDeleteClaimAsync(int? claimid)
        {
            if (claimid == null)
                return NotFound("Không tìm thấy claim");

            userClaim = await _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefaultAsync();

            user = await _userManager.FindByIdAsync(userClaim.UserId);

            if (user == null)
                return NotFound("Không tìm thấy user");

            await _userManager.RemoveClaimAsync(user, new Claim(Input.ClaimType, Input.ClaimValue));

            _notyf.Success("Xóa claim riêng của user " + user.UserName + " thành công");
            StatusMessage = "Xóa claim riêng của user " + user.UserName + " thành công lúc " + DateTimeVN();

            return RedirectToPage("./AddRole", new { Id = user.Id });

        }

        public DateTime DateTimeVN()
        {
            DateTime utcTime = DateTime.UtcNow; // Lấy thời gian hiện tại theo giờ UTC
            TimeZoneInfo vietnamZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time"); // Lấy thông tin về múi giờ của Việt Nam
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(utcTime, vietnamZone); // Chuyển đổi giá trị DateTime từ múi giờ UTC sang múi giờ của Việt Nam

            return vietnamTime;
        }
    }
}

LuanVan/Areas/AdminManage/Pages/User/AddRole.cshtml
@page
@model AddRoleModel
@{
    ViewData["Title"] = @_localization.Getkey("AddRoleForUser");
    var currentCulture = Thread.CurrentThread.CurrentCulture.Name;
    Console.WriteLine(currentCulture);
    if (currentCulture == "vi-VN")
        ViewData["language"] = _localization.Getkey("Vietnamese");
    else if (currentCulture == "en-US")
        ViewData["language"] = _localization.Getkey("English");
    else ViewData["language"] = "";
}


@*<h2>@ViewData["Title"]</h2>*@
<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">@_localization.Getkey("AddRoleForUser")</h1>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <ul class="breadcrumb-nav">
                    <li>
                        <a asp-page="../Home/Index"><i class="lni lni-home"></i> @_localization.Getkey("AdminPage")</a>
                    </li>
                    <li>
                        <a asp-page="Index" asp-area="AdminManage"><i class="lni lni-list"></i> @_localization.Getkey("ListUser")</a>
                    </li>
                    <li>@_localization.Getkey("AddRoleForUser")</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="account-login section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
                <form class="card login-form" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                    <div class="card-body">
                        <div class="title">
                            <h3>@_localization.Getkey("AddRoleForUser")</h3>
                            <p>
                                @_localization.Getkey("AddRoleForUser") <strong>@Model.user.UserName </strong>
                            </p>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                @*Các role gán cho user*@
                                @*<div class="form-floating">*@

                                    @*@Html.ListBoxFor(m=> m.RoleNames, Model.allRoles, new{
                                    id= "id-select-roles",
                                    @class= "form-control"
                                    })
                                    @*<input asp-for="RoleNames" class="form-control" type="" />*@
                                    @*<label asp-for="RoleNames" class="form-label">Các role gán cho user <span class="text-danger">*</span></label>
                                    <span asp-validation-for="RoleNames" class="text-danger"></span>*@
                                   
                                <label asp-for="RoleNames">@_localization.Getkey("RolesAddForUser")  <span class="text-danger">*</span></label>
                                <select asp-for="RoleNames" multiple class="form-select form-control" aria-label="multiple select example">
                                    @foreach (var role in Model.allRoles)
                                    {
                                        <option value="@role">@role</option>
                                    }
                                </select>
                                <span asp-validation-for="RoleNames" class="text-danger p-2"></span>
                                
                            </div>
                            <div class="button">
                                <button class="btn" type="submit">@_localization.Getkey("UpdateStatusAccount")</button>
                                <hr />
                                <a class="btn btn-primary" asp-page="./Index">@_localization.Getkey("BackTo")</a>
                            </div>
                        </div>
                    </div>


                    @*<div class="card-body">
                        <div class="title">
                            <h3>Các claim của user có được từ role</h3>
                            <p>
                                Các claim của user có được từ role
                            </p>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                @if (Model.claimsInRole.Count > 0)
                                {
                                    <ul>
                                        @foreach (var claim in Model.claimsInRole)
                                        {
                                            <li>@claim.ClaimType : @claim.ClaimValue</li>
                                        }
                                    </ul>
                                }
                                else
                                {
                                <ul><strong>Không có claim</strong></ul>
                                }
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="card-body">
                        <div class="title">
                            <h3>Các claim riêng của user</h3>
                            <p class="button">
                                <a class="btn btn-secondary" asp-page="./EditUserRoleClaim" asp-page-handler="AddClaim" asp-route-userid="@Model.user.Id">Thêm claim riêng chỉ thuộc về user</a>
                            </p>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                @if (Model.claimsInUserClaim.Count > 0)
                                {
                                    <ul>
                                        @foreach (var claim in Model.claimsInUserClaim)
                                        {
                                            <li>
                                                <a asp-page="./EditUserRoleClaim" asp-page-handler="EditClaim" asp-route-claimid="@claim.Id">@claim.ClaimType : @claim.ClaimValue</a>

                                            </li>
                                        }
                                    </ul>
                                }
                                else
                                {
                                    <ul><strong>Không có claim riêng</strong></ul>
                                }
                            </div>

                        </div>
                    </div>*@
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

LuanVan/Areas/AdminManage/Pages/User/ConfirmAccount.cshtml
@page
@model ConfirmAccountModel
@{
    ViewData["Title"] = @_localization.Getkey("ConfirmAccount");
    var currentCulture = Thread.CurrentThread.CurrentCulture.Name;
    Console.WriteLine(currentCulture);
    if (currentCulture == "vi-VN")
        ViewData["language"] = _localization.Getkey("Vietnamese");
    else if (currentCulture == "en-US")
        ViewData["language"] = _localization.Getkey("English");
    else ViewData["language"] = "";
}

<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">@_localization.Getkey("ConfirmAccount")</h1>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <ul class="breadcrumb-nav">
                    <li>
                        <a asp-page="../Home/Index"><i class="lni lni-home"></i> @_localization.Getkey("AdminPage")</a>
                    </li>
                    <li>
                        <a asp-page="Index" asp-area="AdminManage"><i class="lni lni-list"></i> @_localization.Getkey("ListUser")</a>
                    </li>
                    <li>@_localization.Getkey("ConfirmAccount")</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<partial name="_StatusMessage" for="StatusMessage" />

<div class="account-login section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
                <form class="card login-form" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                    <div class="card-body">
                        <div class="title">
                            <h3>@_localization.Getkey("ConfirmAccount")</h3>
                            <p>
                                @_localization.Getkey("ConfirmAccount") <strong>@Model.user.UserName</strong>
                            </p>
                        </div>
                        <div class="form-floating">
                            <input asp-for="Input.KhachHangID" class="form-control" aria-required="true" disabled/>
                            <label asp-for="Input.KhachHangID">@_localization.Getkey("MaKH") <span class="text-danger">*</span></label>
                            <span asp-validation-for="Input.KhachHangID" class="text-danger p-2"></span>
                        </div>
                        <div class="form-floating">
                            <select asp-for="Input.Confirm" class="form-control" aria-required="true">
                                <option value="false">@_localization.Getkey("ChuaXacNhan")</option>
                                <option value="true">@_localization.Getkey("DaXacNhan")</option>
                            </select>
                            <label asp-for="Input.Confirm">@_localization.Getkey("TTXN") <span class="text-danger">*</span></label>
                            <span asp-validation-for="Input.Confirm" class="text-danger p-2"></span>
                        </div>
                        <div class="button">
                            <button class="btn" type="submit">@_localization.Getkey("UpdateStatusAccount")</button>
                            <hr />
                            <a class="btn btn-primary" asp-page="./Index">@_localization.Getkey("BackTo")</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

LuanVan/Areas/AdminManage/Pages/User/ExportUserExcel.cshtml
@page
@model ExportUserExcelModel
@{
    ViewData["Title"] = _localization.Getkey("ConfirmPrintBill");
    var currentCulture = Thread.CurrentThread.CurrentCulture.Name;
    Console.WriteLine(currentCulture);
    if (currentCulture == "vi-VN")
        ViewData["language"] = _localization.Getkey("Vietnamese");
    else if (currentCulture == "en-US")
        ViewData["language"] = _localization.Getkey("English");
    else ViewData["language"] = "";
}

@*<h3>Đặt mật khẩu cho thành viên @Model.user.UserName</h3>*@

@*<h2>@ViewData["Title"]</h2>*@
<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">@_localization.Getkey("UserTitle")</h1>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <ul class="breadcrumb-nav">
                    <li>
                        <a asp-page="../Home/Index"><i class="lni lni-home"></i> @_localization.Getkey("AdminPage")</a>
                    </li>
                    <li>
                        <a asp-page="Index" asp-area="AdminManage"><i class="lni lni-list"></i> @_localization.Getkey("ListUser")</a>
                    </li>
                    <li>@_localization.Getkey("ConfirmPrintBill")</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="account-login section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
                <form class="card login-form" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                    <div class="card-body">
                        <div class="title">
                            <h3>@_localization.Getkey("ConfirmPrintBill")</h3>
                            <p>
                                @_localization.Getkey("UserExcel")
                            </p>
                        </div>
                        
                        <div class="button">
                            <button class="btn" type="submit">@_localization.Getkey("PrintBill")</button>
                            <hr />
                            <a class="btn btn-primary" asp-page="./Index">@_localization.Getkey("BackTo")</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

LuanVan/Areas/AdminManage/Pages/User/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}